version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd123
      POSTGRES_DB: payment
    ports:
      - "5432:5432"
    restart: always
